### ISSUE TITLE
DockerRoot & Composer/Python

### ISSUE THREAD

**Issue by if-kenn** [ailispaw/docker-root#11]
Hey, was looking to see if I could start using Docker Compose on DockerRoot. One of the issues is that will need Python on DockerRoot, since it is a very minimal version of Linux, what is the best practice to get new software on an instance of DockerRoot such as Composer or Python.

**Comment by ailispaw** [comment]
Hi @if-kenn ,

I made the package installer for DockerRoot.
https://github.com/ailispaw/docker-root-pkg
It is still a kind of an experimental stage, but you may be able to install python with it.
And also you can install git as well.

Please try it and let me know how you think.

**Comment by if-kenn** [comment]
To keep it simple for now, I found the linux binary for compose here:

https://dl.bintray.com/docker-compose/master/

For now I am just going to see if that can work stand alone, will let you know how it works.

**Comment by ailispaw** [comment]
Or you can use my original docker client, too.
It's portable static go program with the compose command.
https://github.com/ailispaw/talk2docker

**Comment by if-kenn** [comment]
What is advantage of yours vs the official docker compose?

**Comment by ailispaw** [comment]
The biggest advantage is that it can override a configuration in yaml file with command line on runtime.
But it is a little bit old API from the original and some yaml values are different a bit.
https://github.com/ailispaw/talk2docker/blob/master/docs/compose.md

And it supports multiple hosts as well.
Example: https://github.com/ailispaw/consul-cluster/tree/docker-v1.9

**Comment by ailispaw** [comment]
As you found the binaries at https://dl.bintray.com/docker-compose/master/, I'm closing this.
