### ISSUE TITLE
Mounting previous docker-root-data.img

### ISSUE THREAD

**Issue by if-kenn** [ailispaw/docker-root#16]
I am trying to get data off of a docker-root-data.img that is backed up. When I replace the one in the vm directory and then issue a `make up`, it simply makes a new 4GB one. What do I need to do to not have it blow away the old .img?

**Comment by ailispaw** [comment]
Try `touch docker-root-data.img` or something to update a timestamp of the image after replacing.
`make` watches a timestamp of files to keep up to date.

**Comment by ailispaw** [comment]
BTW, please open an issue in appropriate repo. It should be in the `docker-root-xhyve` repo, shouldn't it?

**Comment by if-kenn** [comment]
Yes you are right, I wasn't thinking. Sorry.
