### ISSUE TITLE
Cannot configure network in Vagrantfile

### ISSUE THREAD

**Issue by duro** [ailispaw/docker-root#2]
Here is my Vagrantfile:

```
# Vagrantfile for the proxy VM

Vagrant.configure("2") do |config|

  config.vm.define "zg-docker-host", primary: true do |dhost|

    dhost.vm.box = "ailispaw/docker-root"

    dhost.vm.network :private_network, ip: "192.168.100.200"

    dhost.vm.provider "virtualbox" do |v|
      v.name = "zg-docker-host"
      v.memory = 2048
    end

    dhost.vm.network "forwarded_port", guest: 8080, host: 8080
    dhost.vm.network "forwarded_port", guest: 3000, host: 3000
    dhost.vm.network "forwarded_port", guest: 3232, host: 3232
    dhost.vm.network "forwarded_port", guest: 8888, host: 8888
    dhost.vm.network "forwarded_port", guest: 8003, host: 8003

  end

end
```

When I `vagrant up` I get the following error:

```
Vagrant attempted to execute the capability 'configure_networks'
on the detect guest OS 'linux', but the guest doesn't
support that capability. This capability is required for your
configuration of Vagrant. Please either reconfigure Vagrant to
avoid this capability or fix the issue by creating the capability.
```

**Comment by ailispaw** [comment]
Hi @duro,
Is this at the very first time?
If so, the next `vagrant up` will be fine.

In the case of downloading and loading a Vagrant box at the same time on `vagrant up`,
Vagrant can not load a patch code for vagrant core in the box.

Just `vagrant up` again, or

```
$ vagrant box add ailispaw/docker-root
$ vagrant init -m ailispaw/docker-root
$ vi Vagrantfile
$ vagrant up
```

Please see also https://atlas.hashicorp.com/ailispaw/boxes/docker-root .

**Comment by ailispaw** [comment]
And https://github.com/ailispaw/docker-root-packer

**Comment by ailispaw** [comment]
I should create a Vagrant plugin for this issue.
On `vagrant up` Vagrant checks the guest capabilities before downloading a box, if a box doesn't exist in the local machine.
But if a box exists, Vagrant can load a box and check the guest capabilities.
If a plugin exists, Vagrant loads a plugin first and then do the rest.
