### ISSUE TITLE
Wants a pretty logo

### ISSUE THREAD

**Issue by ailispaw** [ailispaw/docker-root#22]

**Comment by ailispaw** [comment]
![docker-root](https://cloud.githubusercontent.com/assets/10327896/13804772/0b62a4d2-eb93-11e5-90c2-1920fa156ad6.png)

**Comment by wadkar** [comment]
I wish I had some photoshop/artistic skills.

Goodluck! :+1:

**Comment by ailispaw** [comment]
@wadkar Thanks :)

**Comment by ailispaw** [comment]
![dockerroot](https://cloud.githubusercontent.com/assets/10327896/14595021/c3dd4bf4-04f0-11e6-878d-90c897462280.png)

**Comment by ailispaw** [comment]
![dockerroot-logo](https://cloud.githubusercontent.com/assets/10327896/14595025/cbdb455e-04f0-11e6-8e97-fe8900906a03.png)

**Comment by ailispaw** [comment]
![dockerroot-logo-c](https://cloud.githubusercontent.com/assets/10327896/14653345/708af918-062d-11e6-858a-59a2a5529c12.png)

**Comment by ixkaito** [comment]
How is this?

![dockerroot-logo](https://cloud.githubusercontent.com/assets/5457539/14670493/5b4cdd40-0728-11e6-810f-81c8208a2a94.png)
![dockerroot-icon](https://cloud.githubusercontent.com/assets/5457539/14670504/6210e838-0728-11e6-8c2d-d7b7e16290fc.png)
![dockerroot-horizontal](https://cloud.githubusercontent.com/assets/5457539/14670522/6c502eee-0728-11e6-8cbd-fbcef1020469.png)
![dockerroot-vertical](https://cloud.githubusercontent.com/assets/5457539/14670529/70a11a12-0728-11e6-92f8-731322627b59.png)

**Comment by ailispaw** [comment]
OOOOOOOOh! Thank you so much @ixkaito. So cool!!
`/` fits the meaning of root, rather than `√`.
Much cooler than what I imagine.

**Comment by ixkaito** [comment]
Thanks :)

**Comment by ixkaito** [comment]
If you need the data, you can make a repo and I'll send a pull request.

**Comment by ailispaw** [comment]
@ixkaito Thank you. If you don't mind, could you create some samples with other fonts?
I would like to see them including 'PT Serif Bold' I created.
Best regards,

**Comment by ailispaw** [comment]
Maybe I can do it with the image data?
I will create another repo for logo.

**Comment by ailispaw** [comment]
https://github.com/ailispaw/docker-root-logo

**Comment by ixkaito** [comment]
Some choices

![dockerroot-logo-alt-1](https://cloud.githubusercontent.com/assets/5457539/14700077/f0a3e44c-07d7-11e6-9117-f0500586530d.png)
![dockerroot-logo-alt-2](https://cloud.githubusercontent.com/assets/5457539/14700079/f0a4da78-07d7-11e6-96c2-b765ebbf37e7.png)
![dockerroot-logo-alt-3](https://cloud.githubusercontent.com/assets/5457539/14700076/f0a34186-07d7-11e6-871d-a5048ffe1335.png)
![dockerroot-logo-alt-4](https://cloud.githubusercontent.com/assets/5457539/14700075/f0a33696-07d7-11e6-9002-166b5b5d2771.png)
![dockerroot-logo-alt-5](https://cloud.githubusercontent.com/assets/5457539/14700078/f0a46f84-07d7-11e6-9b24-e6b0fa65cd86.png)
![dockerroot-logo-alt-6](https://cloud.githubusercontent.com/assets/5457539/14700080/f0a9d7a8-07d7-11e6-946c-63f734d389af.png)
![dockerroot-logo-alt-7](https://cloud.githubusercontent.com/assets/5457539/14700082/f0cad5fc-07d7-11e6-8eb8-0cbb81c8604f.png)
![dockerroot-logo-alt-8](https://cloud.githubusercontent.com/assets/5457539/14700081/f0c7b192-07d7-11e6-8a3e-fe158cc38b0c.png)

And I sent a pull request to https://github.com/ailispaw/docker-root-logo/pull/1

**Comment by ailispaw** [comment]
Thank you soooo much!!
I like the last one. Is this font the same one of its Icon?

**Comment by ixkaito** [comment]
No, they are different.
I'll make an icon using the same font as the last logo.

**Comment by ailispaw** [comment]
@ixkaito Thanks. I'm not sure, but one font in one image is better, isn't it?

**Comment by ailispaw** [comment]
I just asked you. Anyway it's not your fault, as I requested you about only logo first.

**Comment by ailispaw** [comment]
The original icon looks good as well anyway. :)

**Comment by ixkaito** [comment]
![dockerroot-logo-alt-9](https://cloud.githubusercontent.com/assets/5457539/14732645/9dfa9978-0897-11e6-89ed-b6a81bf398dc.png)
![dockerroot-logo-alt-10](https://cloud.githubusercontent.com/assets/5457539/14732646/9e1be060-0897-11e6-9c08-ba99eb9b6368.png)

These icons and logos have the same font.

> I'm not sure, but one font in one image is better, isn't it?

It depends on the case.
I feel that the first icon is more sophisticated personally.

**Comment by ailispaw** [comment]
Yeah, I feel so, too.
That letter `d` is not what I imagined and it has ugly curve.
The original icon is better, but a bit narrow, I feel.

**Comment by ixkaito** [comment]
I see. I'll make a little change on `d` of the original icon.

**Comment by ailispaw** [comment]
I got an idea.
How's just square like a container instead of `d`?

**Comment by ailispaw** [comment]
Or `d` is not needed at all.

**Comment by ixkaito** [comment]
A little wide.

![dockerroot-icon-v3](https://cloud.githubusercontent.com/assets/5457539/14752902/de62f364-090c-11e6-91b1-c1dc5c99b5d4.png)

More wide.

![dockerroot-icon-v4](https://cloud.githubusercontent.com/assets/5457539/14752904/de9b0ba0-090c-11e6-9ea3-5ab7c3fa3c93.png)

Rounded square

![dockerroot-icon-v5](https://cloud.githubusercontent.com/assets/5457539/14752906/dea30a76-090c-11e6-8875-bd99bf0478f3.png)

Square

![dockerroot-icon-v6](https://cloud.githubusercontent.com/assets/5457539/14752905/dea0b320-090c-11e6-8d57-a25c31cdecef.png)

> Or `d` is not needed at all.

There's a very similar icon: https://we-are-root.com/

I still like the original one or v3 personally.

**Comment by ixkaito** [comment]
Another idea.

![dockerroot-icon-v7](https://cloud.githubusercontent.com/assets/5457539/14753328/b07eadc8-090f-11e6-9b30-d384f8feee64.png)

**Comment by ailispaw** [comment]
@ixkaito Thank you for the images and taking your time.

> There's a very similar icon: https://we-are-root.com/

Oh! It's nice though...

Let me think.

**Comment by ailispaw** [comment]
I adopt `d` from Docker logo which has a perfect circle in `d`.
It's just a try, so the width of `d` and `/` are deferent due to my poor image handling...

![dockerroot-logo-alt-8-5](https://cloud.githubusercontent.com/assets/10327896/14757411/0e90ced6-08a8-11e6-992e-563f3a472a82.png)

![dockerroot-logo-alt-8-6](https://cloud.githubusercontent.com/assets/10327896/14757413/14ccc73c-08a8-11e6-85f8-b225477d83d2.png)

The colors are from Docker and Buildroot each.

**Comment by ixkaito** [comment]
Actually, I did the `d` from Docker logo as a test, but it was not stylish enough that I expected, so I didn't show you. If you love it, it's fine. However, I don't recommend you the color version. It seems strange from a viewpoint of a designer. I recommend single color and not to color the letters of the icon but the background. If you want a color logo/icon, please tell me the color theme of DockerRoot. I'll give it a try.

![dockerroot-logo-v2-1](https://cloud.githubusercontent.com/assets/5457539/14769386/0b10b0aa-0a92-11e6-98cf-eb38fd137f89.png)

![dockerroot-logo-v2-2](https://cloud.githubusercontent.com/assets/5457539/14769385/0b0ef396-0a92-11e6-9e07-6ec0bad1938a.png)

![dockerroot-logo-v2-3](https://cloud.githubusercontent.com/assets/5457539/14769384/0ad29586-0a92-11e6-9882-ca3c8c8dec28.png)

![dockerroot-logo-v2-4](https://cloud.githubusercontent.com/assets/5457539/14769383/0ad12ffc-0a92-11e6-8e2a-4680af252d0b.png)

**Comment by ailispaw** [comment]
@ixkaito Thank you soooo much!!
I understand, but I would like to see the color version, too.
And also how do you think about the size of the area `d/` in the square?
Is it OK? Or big or small. I guess it should be a quoter of the square. maybe not.

**Comment by ailispaw** [comment]
The size is fine with the original one.

**Comment by ixkaito** [comment]
Got it. (I tested several sizes of `d/`. I felt that a quarter is a little small.)
What color do you like? It doesn't have to be RGB or CMYK code. Color name is OK such as red, blue, green, cyan, magenta, yellow, orange, etc.

**Comment by ailispaw** [comment]
Yeah, on my second thought, I feel same as you about the size.

**Comment by ailispaw** [comment]
Could you capture colors from my sample?
Or let me check the code of the colors.

**Comment by ailispaw** [comment]
FYI: I put links to the icon/mascot of Docker and Buildroot.
https://www.docker.com/sites/default/files/legal/docker_media_kit_jan_2016.zip
https://buildroot.org/downloads/manual/logo.png

**Comment by ailispaw** [comment]
Docker Blue: 59, 169, 229
Buildroot Yellow: 246, 180, 39 (more brighter, 255,175,0 is fine, too)

**Comment by ailispaw** [comment]
I like stylish, but I prefer cute to stylish in this case.
That's why I chose the font rather than the original one.

**Comment by ailispaw** [comment]
I'm sorry for this over request. @ixkaito

**Comment by ailispaw** [comment]
Oh,

> Do not:
> Use the word Docker as the first word in the name of your website or domain name, application or product, business name, social media and other online accounts, including Twitter, Facebook, or GitHub

https://www.docker.com/brand-guidelines

**Comment by ailispaw** [comment]
＼(^o^)／ It seems I have to rename it. orz

**Comment by ailispaw** [comment]
dee-root?

**Comment by ailispaw** [comment]
@ixkaito I'm sorry for this. It's my fault.
I love the logo so much, but I will rethink it.

**Comment by ixkaito** [comment]
OMG!
How about RootDocker?

**Comment by ixkaito** [comment]
Maybe it's better not to use the `d` from Docker logo.

**Comment by ailispaw** [comment]
I'm thinking a totally different name.

Chiatta

**Comment by ailispaw** [comment]
Currently it uses Docker engine, but it may use another engine in the future.
It's a good time to change the name.

**Comment by ixkaito** [comment]
I see. Looking forward to it :)

**Comment by ailispaw** [comment]
@ixkaito Thank you so much for your work anyway. :)

**Comment by ailispaw** [comment]
Closing for now.
