### ISSUE TITLE
NFS compatibility ?

### ISSUE THREAD

**Issue by cedvan** [ailispaw/docker-root#23]
Hi,

This box is compatible with the vagrant synced folder nfs type ?

See you

**Comment by ailispaw** [comment]
this one? https://atlas.hashicorp.com/ailispaw/boxes/docker-root
Yes.

**Comment by ailispaw** [comment]
Please open it at https://github.com/ailispaw/docker-root-packer instead and see also.

**Comment by cedvan** [comment]
cf. https://github.com/ailispaw/docker-root-packer/issues/3
