### ISSUE TITLE
Make a permanent folder

### ISSUE THREAD

**Issue by cedvan** [ailispaw/docker-root#28]
Hi,

How make a permanent folder ?

I create an folder `/var/lib/rancher` with files in VM, after `vagrant halt` and `vagrant up`, folder disappeared.

Thank you

**Comment by ailispaw** [comment]
docker-root.box has 40GB HDD and mounts it at /mnt/sda1 (/dev/sda1).
https://github.com/ailispaw/docker-root-packer#dockerroot-packer-for-virtualbox-and-qemu

You can make any folder under the /mnt/sda1 as a persistent one.

**Comment by cedvan** [comment]
Yes, I already fix my problem, not had time to update issue :wink:

Thank you !

**Comment by cedvan** [comment]
Maybe add information about `/mnt/sda1` in Readme.md ?

**Comment by cedvan** [comment]
I use : 

```
node.vm.provision "shell",
    inline: "rm -f /var/lib/docker && rm -f /var/lib/docker-root && mv /var/lib/* /mnt/sda1/var/lib/ && ln -s /mnt/sda1/var/lib /var/lib"
```

Because, I can't create symbolic link `/var/lib/rancher` on provisioning. Docker container want to create it

**Comment by cedvan** [comment]
Provision is execute only first up. how can I make persistent the symbolic link ?

**Comment by cedvan** [comment]
provision is execute only first up

**Comment by cedvan** [comment]
Possible add `/var` overall persistent on docker-root please ?

Would be more clean and logic :wink:

**Comment by ailispaw** [comment]
/var/lib/docker && /var/lib/docker-root are reserved by DockerRoot.
Please use as below instead.

```
  node.vm.provision "shell",
    inline: "mkdir -p /mnt/sda1/var/lib/rancher && \
      rm -f /var/lib/rancher && ln -s /mnt/sda1/var/lib/rancher /var/lib/rancher"

```

**Comment by cedvan** [comment]
Impossible sorry, rancher-agent want create /var/lib/rancher. Is `/var/lib/rancher` exist, failed start :worried:

**Comment by ailispaw** [comment]
You can put any scripting into /var/lib/docker-root/start.sh.
https://github.com/ailispaw/docker-root/blob/master/docs/customization.md#customizing-init-scripts-on-booting-up

Or you can use `run: "always" option for a Vagrant provisioner.

**Comment by ailispaw** [comment]
You see `rm -f /var/lib/rancher` in my script.

**Comment by ailispaw** [comment]
Oh, rancher-agent dose!

**Comment by ailispaw** [comment]
I think rancher-agent should work in that situation.

**Comment by cedvan** [comment]
Ok for script to make persistent symbolic link with init.d, I'll try, thank you !

But no solution to first start VM. rancher-agent want create `/var/lib/rancher` on first run, so I can't create symbolic link before run :cry:

**Comment by ailispaw** [comment]
You may want to try `vagrant-triggers` to run it after up.

```
  if Vagrant.has_plugin?("vagrant-triggers") then
    config.trigger.after [:up, :resume] do
      info "Adjusting datetime after suspend and resume."
      run_remote "sudo sntp -4sSc pool.ntp.org; date"
    end
  end
```

**Comment by ailispaw** [comment]
It was wrong.

I just got an idea.
You can make an init script in the SysV manner to backup/restore the data in `/var/lib/rancher` instead of symlink.

**Comment by ailispaw** [comment]
Anyway, rancher-agent should work in such a situation.

**Comment by cedvan** [comment]
Oh great idea ! I try :smiley:

**Comment by ailispaw** [comment]
Wait a minute.
`-v /var/lib/rancher:/var/lib/rancher rancher/agent:v0.9.2` means that `/var/lib/rancher` has already existed at run the container. ??? I don't understand that failure.

**Comment by cedvan** [comment]
Ok works !

But, if the VM crash, no backup :worried:

**Comment by cedvan** [comment]
Yes, this command to add custom host :

```
sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v0.10.0 https://infra.cedvan.com/v1/scripts/4A21993727DD77639CA1:1458604800000:hBFQhNHEkdXRKy8ZKtg3ItAw2gk
```

means that `/var/lib/rancher` already exist with symbolic link create before first run

**Comment by cedvan** [comment]
Ok great !

My solution :

lib-persistent-folder.sh

```
#!/bin/sh
#
# Configure lib persistent folder....
#


case "$1" in
  install)
        echo "Install lib persistent folder..."
        rm -f /var/lib/docker
        rm -f /var/lib/docker-root
        cp -rf /var/lib/* /mnt/sda1/var/lib/
        rm -rf /var/lib
        ln -s /mnt/sda1/var/lib /var/lib
        ;;
  start)
    echo "Mount lib persistent folder..."
        rm -rf /var/lib
    ln -s /mnt/sda1/var/lib /var/lib
    ;;
  stop)
    printf "Unmount lib persitent folder..."
    rm -f /var/lib
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: $0 {install|start|stop|restart}"
    exit 1
esac

exit $?
```

Vagrantfile

```
...

order = 60
script_name_source = "lib-persistent-folder.sh"
script_name_destination = "S#{order}lib-persistent-folder"
node.vm.provision "file", source: "./#{script_name_source}", destination: "/tmp/#{script_name_destination}"
node.vm.provision "shell",
inline: "mv /tmp/#{script_name_destination} /etc/init.d/#{script_name_destination} && chmod +x /etc/init.d/#{script_name_destination} && /etc/init.d/#{script_name_destination} install"

...
```

**Comment by cedvan** [comment]
With this solution data saved on crash :)

**Comment by cedvan** [comment]
Why do you not make persistent the folder `/var` completely ?

**Comment by ailispaw** [comment]
It is not a good idea to remove `/var/lib/docker` on provision while running Docker daemon.

I just follow the boot2docker way about `/var/lib/docker`.

**Comment by cedvan** [comment]
Ok, it is better to stop docker daemon, delete, create the symbolic link `/var/lib` and restart the docker daemon ?

```
  install)
        echo "Install lib persistent folder..."
        /etc/init.d/docker stop
        rm -f /var/lib/docker
        rm -f /var/lib/docker-root
        cp -rf /var/lib/* /mnt/sda1/var/lib/
        rm -rf /var/lib
        ln -s /mnt/sda1/var/lib /var/lib
        /etc/init.d/docker start
        ;;
```

**Comment by ailispaw** [comment]
Those script should be in `start` for every boot.
DockerRoot /init will create symlinks to `/var/lib/docker` and `/var/lib/docker-root` again on boot.

BTW,
Why don't you open an issue for this at `rancher/agent` repo?

**Comment by ailispaw** [comment]
In `start`, you don't need to stop/start Docker daemon, because Docker daemon stops in the init.d process.

**Comment by cedvan** [comment]
Issue to rancher/rancher is open https://github.com/rancher/rancher/issues/4073 :wink:

**Comment by cedvan** [comment]
Step `install` is executed on provisioning, so docker daemon is running. Stop/start docker is necessary no ?
Steps `start` and `stop` executed by init.d, so not need stop/start docker

**Comment by ailispaw** [comment]
> Step install is executed on provisioning, so docker daemon is running.
> Stop/start docker is necessary.

Yes

> Steps start and stop executed by init.d, so not need stop/start docker

No, you don't need.

**Comment by cedvan** [comment]
Ok, so my solution is good ?
(Just to wait that rancher/rancher solve problem)

**Comment by ailispaw** [comment]
Let me see the final version of your script. Probably fine.

**Comment by cedvan** [comment]
lib-persistent-folder.sh

```
#!/bin/sh
#
# Configure lib persistent folder....
#

case "$1" in
  install)
        echo "Install lib persistent folder..."
        /etc/init.d/docker stop
        rm -f /var/lib/docker
        rm -f /var/lib/docker-root
        cp -rf /var/lib/* /mnt/sda1/var/lib/
        rm -rf /var/lib
        ln -s /mnt/sda1/var/lib /var/lib
        /etc/init.d/docker start
        ;;
  start)
    echo "Mount lib persistent folder..."
        rm -rf /var/lib
    ln -s /mnt/sda1/var/lib /var/lib
    ;;
  stop)
    printf "Unmount lib persitent folder..."
    rm -f /var/lib
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: $0 {install|start|stop|restart}"
    exit 1
esac

exit $?
```

Vagrantfile

```
...

order = 60
script_name_source = "lib-persistent-folder.sh"
script_name_destination = "S#{order}lib-persistent-folder"
node.vm.provision "file", source: "./#{script_name_source}", destination: "/tmp/#{script_name_destination}"
node.vm.provision "shell",
    inline: "mv /tmp/#{script_name_destination} /etc/init.d/#{script_name_destination} && chmod +x /etc/init.d/#{script_name_destination} && /etc/init.d/#{script_name_destination} install"

...
```

**Comment by ailispaw** [comment]
I guess,

```
        rm -f /var/lib/docker
        rm -f /var/lib/docker-root
        cp -rf /var/lib/* /mnt/sda1/var/lib/
        rm -rf /var/lib
        ln -s /mnt/sda1/var/lib /var/lib
```

should be in `start` for every boot.

**Comment by ailispaw** [comment]
Did you try `-v /mnt/sda1/var/lib/rancher:/var/lib/rancher` ?

**Comment by cedvan** [comment]
> should be in start for every boot.

Why ?

> Did you try -v /mnt/sda1/var/lib/rancher:/var/lib/rancher ?

Lol, no I don't try, I wanted to keep rancher default config. But I'll try :smile:

**Comment by cedvan** [comment]
Works :stuck_out_tongue_closed_eyes: !

**Comment by ailispaw** [comment]
> should be in start for every boot.
> Why ?

DockerRoot /init script creates symlinks `/var/lib/docker` and `/var/lib/docker-root` before init.d scripts on every boot.

**Comment by cedvan** [comment]
Ok, I understand

**Comment by ailispaw** [comment]
> Why do you not make persistent the folder /var completely ?

Other system processes like syslog and programs use under `/var`, so it's not good to move completely even on boot.
