### ISSUE TITLE
Hostname should be set before docker start

### ISSUE THREAD

**Issue by cedvan** [ailispaw/docker-root#31]
Hi,

After commands `vagrant halt` and `vagrant up`, docker start before hostname initialisation.
So on rancher server, the host have `docker-root` hostname instead of `node-1`

Hostname should be set before docker start, no ?

Thank you

**Comment by ailispaw** [comment]
The answer is yes, but it seems not able to set it like that with Vagrant.

**Comment by cedvan** [comment]
Why ?

**Comment by ailispaw** [comment]
Vagrant sets hostname with ssh after boot up.

**Comment by cedvan** [comment]
All time or only after first run ?

But in any case, what is the problem ? In the worst case vagrant overload the hostname configured in /mnt/sda1, but it is not serious problem, no ?

**Comment by ailispaw** [comment]
All time on up.

```
==> docker-root: Booting VM...
==> docker-root: Waiting for machine to boot. This may take a few minutes...
    docker-root: SSH address: 127.0.0.1:2222
    docker-root: SSH username: docker
    docker-root: SSH auth method: private key
==> docker-root: Machine booted and ready!
==> docker-root: Setting hostname...
```

Also i'm not sure what the problem is, because I don't understand how the rancher server works on boot.

**Comment by ailispaw** [comment]
I might found an issue on DockerRoot side.
Let me check.

**Comment by cedvan** [comment]
Ok :smiley:

**Comment by ailispaw** [comment]
For workaround, you can put `/bin/hostname -F /etc/hostname` in `/var/lib/docker-root/init.sh`.

**Comment by ailispaw** [comment]
I will release the next version tomorrow.

**Comment by cedvan** [comment]
Your tricks works like a charm ! Thank you :smile:

**Comment by ailispaw** [comment]
@cedvan Thank you so much for letting me know this issue.

**Comment by ailispaw** [comment]
Fixes at https://github.com/ailispaw/docker-root/commit/001655f2ef31acc59112403b57c321f06ac1f45a

**Comment by cedvan** [comment]
Great !
