### ISSUE TITLE
How to set timezone

### ISSUE THREAD

**Issue by cedvan** [ailispaw/docker-root#32]
Hi,

I try add 

```
config.vm.provision "timesync", type: "shell", run: "always" do |sh|
    sh.inline = "sntp -4sSc fr.pool.ntp.org; date"
end
```

But date stay to UTC :(, an idea ?

**Comment by ailispaw** [comment]
@cedvan 
You just changed a location of NTP server, not timezone.
You can set timezone as below, but I recommend 'UTC' to use Docker.

```
[docker@docker-root ~]$ sudo pkg install tzdata -e BR2_TARGET_TZ_ZONELIST=default
[docker@docker-root ~]$ echo 'Europe/Paris' | sudo tee /etc/timezone
Europe/Paris
[docker@docker-root ~]$ sudo cp -L /usr/share/zoneinfo/Europe/Paris /etc/localtime
[docker@docker-root ~]$ date
Thu Mar 31 01:48:15 CEST 2016
```

To set back to 'UTC', use 'Etc/UTC' instead of 'Europe/Paris'.

**Comment by cedvan** [comment]
Thank you, I"ll try !

> You can set timezone as below, but I recommend 'UTC' to use Docker.

Why ?

**Comment by ailispaw** [comment]
I read somewhere in CoreOS repo. Sorry I don't remember that.

**Comment by ailispaw** [comment]
I'm not sure, but it might be good if you use same timezone on each servers in a cluster.

**Comment by ailispaw** [comment]
CoreOS: Configuring Date & Timezone (NTP)
https://coreos.com/os/docs/latest/configuring-date-and-timezone.html#recommended-utc-time

**Comment by ailispaw** [comment]
It might be specific to CoreOS. etcd, fleet or something.

**Comment by ailispaw** [comment]
Added pre-built tzdata package in https://github.com/ailispaw/docker-root-pkg/releases/tag/1.3.6 for convenience.

**Comment by cedvan** [comment]
Great ! thank you :smiley: 

>  I'm not sure, but it might be good if you use same timezone on each servers in a cluster.

Yes, I want use same timezone between my nodes in my cluster
