### ISSUE TITLE
How restart sshd daemon to change the default port ?

### ISSUE THREAD

**Issue by cedvan** [ailispaw/docker-root#35]
Hi,

I need to free up port 22. So I need change sshd default port.

```
$ssh_port = "22#{i}"
node.vm.provision "shell",
    inline: "sed -i '/#Port/c\Port #{$ssh_port}' /etc/ssh/sshd_config && sudo kill $(ps aux | grep /usr/sbin/sshd | head -1 | awk '{print $1}') && sudo /usr/sbin/sshd"
node.vm.network :forwarded_port, guest: $ssh_port, host: $ssh_port, id: "ssh"
node.ssh.port = $ssh_port
```

I need replace `kill` by clean restart, how can I do please ?

Thank you !

**Comment by ailispaw** [comment]
After modifying `/etc/ssh/sshd_config`, you have to add the following(
in case of Port 2200) into Vagrantfile and just `vagrant reload`.

```
  config.ssh.guest_port = 2200
  config.vm.network :forwarded_port, guest: 2200, host: 2200
```

I'm wondering why you need to free port 22 by the way.

**Comment by cedvan** [comment]
Ok, I tried :

```
$ssh_port = "22%02d" % i
node.vm.provision "shell",
    inline: "sed -i '/#Port/c\Port #{$ssh_port}' /etc/ssh/sshd_config"
node.vm.network :forwarded_port, guest: $ssh_port, host: $ssh_port, id: "ssh"
node.ssh.port = $ssh_port
node.ssh.guest_port = $ssh_port
```

result : 

```
==> cedvanNode1: Forwarding ports...
    cedvanNode1: 2375 (guest) => 2375 (host) (adapter 1)
    cedvanNode1: 2201 (guest) => 2201 (host) (adapter 1)
==> cedvanNode1: Running 'pre-boot' VM customizations...
==> cedvanNode1: Booting VM...
==> cedvanNode1: Waiting for machine to boot. This may take a few minutes...
    cedvanNode1: SSH address: 127.0.0.1:2201
    cedvanNode1: SSH username: docker
    cedvanNode1: SSH auth method: private key
    cedvanNode1: Warning: Remote connection disconnect. Retrying...
    cedvanNode1: Warning: Remote connection disconnect. Retrying...
```

> I'm wondering why you need to free port 22.

I run rancher loadbalancer container for redirect to tcp/http containers. I would like to mount port 22 on VM to port 22 on loadbalancer to call containers with ssh port 22 (especially for Gitlab).

**Comment by ailispaw** [comment]
@cedvan It's not automatic thing.

On `vagrant up`, which uses port 22;

```
$ssh_port = "22%02d" % i
node.vm.provision "shell",
    inline: "sed -i '/#Port/c\Port #{$ssh_port}' /etc/ssh/sshd_config"
```

And then, on `vagrant reload`;

```
$ssh_port = "22%02d" % i
# node.vm.provision "shell",
#    inline: "sed -i '/#Port/c\Port #{$ssh_port}' /etc/ssh/sshd_config"
node.vm.network :forwarded_port, guest: $ssh_port, host: $ssh_port, id: "ssh"
node.ssh.port = $ssh_port
node.ssh.guest_port = $ssh_port
```

**Comment by cedvan** [comment]
With reload, VM works ! :smiley: 

Possible to operate without a reload ? With a restart of the sshd daemon on first up ?

**Comment by ailispaw** [comment]
If you don't need `vagrant ssh`, you may be able to do `sudo reboot` in the VM instead of `vagrant reload`,
and use `ssh docker@<ip address> -p 220x -i ./.vagrant/machines/<vm-name>/virtualbox/private_key -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no`

`<ip address>`: static IP Address of the VM
`<vm name>`: the name of the VM which you set `config.vm.define` in the Vagrantfile.

In this case, you can not use `vagrant ssh`, because it doesn't have port forwarding to 220x without `vagrant reload`.

**Comment by cedvan** [comment]
`vagrant reload` or `sudo reboot` are not long-term solutions :confused:

**Comment by cedvan** [comment]
Works fine with : 

```
$ssh_port = "22%02d" % i
node.vm.provision "shell",
    inline: "sed -i '/#Port/c\Port #{$ssh_port}' /etc/ssh/sshd_config && sudo kill $(ps aux | grep /usr/sbin/sshd | head -1 | awk '{print $1}') && sudo /usr/sbin/sshd"
```

`vagrant ssh` is broke, but not critical

**Comment by ailispaw** [comment]
I will consider adding a script to start/stop sshd in the `/etc/init.d/`.

**Comment by ailispaw** [comment]
Just released v1.3.9.
Now you can restart sshd with just `sudo /etc/init.d/S50sshd restart`.

**Comment by cedvan** [comment]
Really nice ! :smiley:

Thanks you man ! Great job :)

**Comment by cedvan** [comment]
Hi,

Problem isn't solved. Need `vagrant up`, edit `Vagranfile` and `vagrant reload` to works... :confused:

**Comment by ailispaw** [comment]
@cedvan It seems a limitation of Vagrant.

You may be able to use `VBoxMange` directly to setup port forwarding without `vagrant reload`.
And/or something like the following may help you,  but it seems still to need `vagrant reload`.

```
$ssh_port = "22%02d" % i
if ARGV[0] == "up"
  node.vm.provision "shell",
      inline: "sed -i '/#Port/c\Port #{$ssh_port}' /etc/ssh/sshd_config && sudo sudo /etc/init.d/S50sshd restart"
else
  node.ssh.guest_port = $ssh_port
  node.vm.network :forwarded_port, guest: $ssh_port, host: $ssh_port, id: "ssh"
end
```

**Comment by ailispaw** [comment]
It seems not DockerRoot specific.
You had better to ask at Vagrant community.

**Comment by cedvan** [comment]
Yes, thank you :smiley: !
