### ISSUE TITLE
Adding Insecure Registries

### ISSUE THREAD

**Issue by if-kenn** [ailispaw/docker-root#4]
I was hoping you might give me some help on the best way to add insecure registries.

I think I want to change /var/lib/docker-root/profile and simply add this to it:

DOCKER_EXTRA_ARGS="INSECURE_REGISTRY='--insecure-registry dockreg.example.com:5000'"

Do I need use makehdd to make this permanent?

The other issue that will effect this is the fact that I cannot even telnet to port 5000 on my registry where on my Mac I can, from DockerRoot I get "Connection closed by foreign host". Can you think why this would happen?

Thanks!

**Comment by ailispaw** [comment]
Hi @if-kenn , Thank you so much for using DockerRoot.

> DOCKER_EXTRA_ARGS="INSECURE_REGISTRY='--insecure-registry dockreg.example.com:5000'"

I guess you mean the following without `INSECURE_REGISTRY`.

```
DOCKER_EXTRA_ARGS="--insecure-registry dockreg.example.com:5000"
```

> Do I need use makehdd to make this permanent?

Yes. You have to make a HDD to make it persistent.  
Cf.) https://github.com/ailispaw/docker-root/blob/master/docs/customization.md

Once you make a HDD with the label `DOCKERROOT-DATA`, you can modify the profile any time and reboot to effect it.

> The other issue that will effect this is the fact that I cannot even telnet to port 5000 on my registry where on my Mac I can, from DockerRoot I get "Connection closed by foreign host". Can you think why this would happen?

I will figure it out.

BTW,
What kind of infrastructure (hypervisor) do you use?

**Comment by if-kenn** [comment]
Thanks for your quick reply.

Yes sorry copy and paste error on the registry.

I am using xhyve.

Let me know if you want me to open the network issue as a separate Github issue.

**Comment by ailispaw** [comment]
Oh, xhyve!
Do you use https://github.com/ailispaw/docker-root-xhyve ?
It has a HDD by default.

I guess the issue is related to xhyve. 
Let me check.

**Comment by if-kenn** [comment]
Yes I have been running your docker-root-xhyve. Files I changed did not persist through halt and start again so I thought it was a HDD thing.

**Comment by ailispaw** [comment]
Hmm. That's strange.
I can add DOCKER_EXTRA_ARGS to profile and enable it after reboot.

How's `df` on DockerRoot VM?

```
[docker@docker-root ~]$ df
Filesystem           1K-blocks      Used Available Use% Mounted on
devtmpfs                506648         0    506648   0% /dev
tmpfs                   511976         0    511976   0% /run
cgroup                  511976         0    511976   0% /sys/fs/cgroup
/dev/vda1              2949500      4900   2767400   0% /mnt/vda1
overlay                2949500      4900   2767400   0% /etc
```

**Comment by if-kenn** [comment]
```
Filesystem           1K-blocks      Used Available Use% Mounted on
devtmpfs                506648         0    506648   0% /dev
tmpfs                   511976         0    511976   0% /run
cgroup                  511976         0    511976   0% /sys/fs/cgroup
/dev/vda1              2949500    203120   2569180   7% /mnt/vda1
overlay                2949500    203120   2569180   7% /etc
```

**Comment by ailispaw** [comment]
That looks good.
Let me see your /var/lib/docker-root/profile?

```
[docker@docker-root ~]$ cat /var/lib/docker-root/profile
DOCKER_HOST="-H unix:// -H tcp://0.0.0.0:2375"
DOCKER_EXTRA_ARGS="--insecure-registry dockreg.example.com:5000"
```

**Comment by ailispaw** [comment]
How about this?

```
[docker@docker-root lib]$ ls -l /var/lib
total 0
lrwxrwxrwx    1 root     root            24 Sep 24 21:02 docker -> /mnt/vda1/var/lib/docker/
lrwxrwxrwx    1 root     root            29 Sep 24 21:02 docker-root -> /mnt/vda1/var/lib/docker-root/
drwxr-xr-x    2 root     root            40 Sep 22 00:03 misc/
drwx--x--x    3 root     root            60 Sep 21 23:44 sudo/
```

**Comment by if-kenn** [comment]
```
total 0
lrwxrwxrwx    1 root     root            24 Sep 24 18:51 docker -> /mnt/vda1/var/lib/docker/
lrwxrwxrwx    1 root     root            29 Sep 24 18:51 docker-root -> /mnt/vda1/var/lib/docker-root/
drwxr-xr-x    2 root     root            40 Sep 22 00:03 misc/
drwx--x--x    3 root     root            60 Sep 21 23:44 sudo/
```

**Comment by ailispaw** [comment]
Hmm.. That should be fine.

**Comment by ailispaw** [comment]
I got this after reboot.

```
[docker@docker-root lib]$ ps ax | grep docker
    1 root     docker daemon -D -s overlay -g /var/lib/docker -H unix:// -H tcp://0.0.0.0:2375 --insecure-registry dockreg.example.com:5000
```

**Comment by ailispaw** [comment]
Just in case, could you make sure to have the latest master of docker-root-xhyve?

**Comment by if-kenn** [comment]
Great, looks like it is staying persistent though reboots and I can pull from my private registry. I don't know what changed.

Telnet'ing to port 5000 now appears to work as well. So I guess it is a non-issue, I just don't understand why it changed.

**Comment by if-kenn** [comment]
FYI, was already on latest master.

**Comment by ailispaw** [comment]
Glad to hear that. :)

**Comment by if-kenn** [comment]
Closing this issue as we can use the 

```
DOCKER_EXTRA_ARGS="--insecure-registry dockreg.example.com:5000"
```

as mentioned above.
